/**
 * Forensic Evidence and Executive PDF Certificate Export Service (SOLID - SRP)
 * Handles Section 65B Indian Evidence Act certification and Executive reporting.
 */
import { jsPDF } from 'jspdf';

/**
 * Generates an SCRB Section 65B Certified Evidence Packet PDF
 */
export function exportEvidencePacketPDF(data) {
  if (!data) return;
  const doc = new jsPDF();
  doc.setDrawColor(59, 130, 246);
  doc.setLineWidth(1);
  doc.rect(5, 5, 200, 287);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text('KARNATAKA STATE POLICE', 105, 20, { align: 'center' });

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text('STATE CRIME RECORDS BUREAU (SCRB) - EVIDENCE CERTIFICATE', 105, 26, { align: 'center' });
  doc.line(15, 30, 195, 30);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30);
  doc.text('1. DIGITAL EVIDENCE METADATA & HASHES', 15, 40);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Image Hash (SHA-256): ${data.sha256 || 'N/A'}`, 15, 48);
  doc.text(`Timestamp: ${data.timestamp || new Date().toISOString()}`, 15, 54);
  doc.text(`Threat Category: ${data.threat_category || 'Cyber Fraud'}`, 15, 60);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('2. NETWORK & INFRASTRUCTURE INTELLIGENCE', 15, 72);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Resolved IP Address: ${data.ip_address || 'N/A'}`, 15, 80);
  doc.text(`Hosting Provider / ISP: ${data.hosting_provider || 'N/A'}`, 15, 86);
  doc.text(`Autonomous System (ASN): ${data.asn || 'N/A'}`, 15, 92);
  doc.text(`Country / Location: ${data.country || 'N/A'}`, 15, 98);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('3. GEOLOCATION RADAR CO-ORDINATES', 15, 110);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const gps = data.gps || {};
  doc.text(`Latitude: ${gps.latitude || 'N/A'}° N`, 15, 118);
  doc.text(`Longitude: ${gps.longitude || 'N/A'}° E`, 15, 124);
  doc.text(`Resolved Sector Name: ${gps.location_name || 'N/A'}`, 15, 130);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('4. EXTRACTED FINANCIAL INDICATORS & MULE ACCOUNTS', 15, 142);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const indicators = data.extracted_indicators || {};
  doc.text(`UPI IDs: ${(indicators.upi_ids || []).join(', ') || 'None'}`, 15, 150);
  doc.text(`Phone Numbers: ${(indicators.phone_numbers || []).join(', ') || 'None'}`, 15, 156);
  doc.text(`Mule Bank Accounts: ${(indicators.bank_accounts || []).join(', ') || 'None'}`, 15, 162);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('5. LEGAL ADMISSIBILITY & CERTIFICATION', 15, 175);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('Certified under Section 65B of the Indian Evidence Act, 1872 / Section 63 of BSA 2023.', 15, 183);
  doc.text('Generated by KSP Sentinel AI - State Crime Records Bureau (SCRB) Automated Evidence Engine.', 15, 189);

  doc.save(`Evidence_Packet_${(data.ip_address || '127_0_0_1').replace(/\./g, '_')}.pdf`);
}

/**
 * Generates an Executive Briefing / Conversation Summary Report PDF
 */
export function exportChatExecutiveReportPDF({ messages, voiceLang = 'en-IN' }) {
  const doc = new jsPDF();
  const now = new Date().toLocaleString();

  doc.setDrawColor(37, 99, 235);
  doc.setLineWidth(1);
  doc.rect(5, 5, 200, 287);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.setTextColor(15, 23, 42);
  doc.text('KARNATAKA STATE POLICE • SENTINEL AI COMMAND', 105, 18, { align: 'center' });

  doc.setFontSize(10);
  doc.setTextColor(37, 99, 235);
  doc.text('KSP COMMAND AI EXECUTIVE REPORT', 105, 24, { align: 'center' });

  doc.setDrawColor(203, 213, 225);
  doc.setLineWidth(0.5);
  doc.line(15, 28, 195, 28);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text(
    `Generated: ${now}  |  Language: ${voiceLang === 'kn-IN' ? 'Kannada (kn-IN)' : 'English (en-IN)'}  |  Audit: SECURE`,
    15,
    34
  );

  let currentY = 42;

  doc.setFillColor(239, 246, 255);
  doc.rect(15, currentY, 180, 36, 'F');
  doc.setDrawColor(191, 219, 254);
  doc.rect(15, currentY, 180, 36, 'S');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(30, 58, 138);
  doc.text('INCIDENT COMMAND LOGS & AUDITED TELEMETRY', 20, currentY + 8);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text(`Total Intelligence Exchanges: ${messages.length}`, 20, currentY + 16);
  doc.text(`Primary Jurisdiction: Karnataka State Police Command Grid`, 20, currentY + 22);
  doc.text(`Section 65B Hash Authentication: VERIFIED VALID`, 20, currentY + 28);

  currentY += 46;

  messages.slice(-8).forEach((m) => {
    if (currentY > 260) {
      doc.addPage();
      currentY = 20;
    }
    const isBot = m.sender === 'bot';
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(isBot ? 37 : 15, isBot ? 99 : 23, isBot ? 235 : 42);
    doc.text(isBot ? `[SENTINEL AI - ${m.agent_label || 'Command Agent'}]:` : `[INVESTIGATING OFFICER]:`, 15, currentY);
    currentY += 5;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(51, 65, 85);
    const cleanText = (m.text || '').replace(/<[^>]*>?/gm, '').replace(/&nbsp;/g, ' ').substring(0, 260);
    const splitLines = doc.splitTextToSize(cleanText, 175);
    doc.text(splitLines, 15, currentY);
    currentY += splitLines.length * 4 + 4;
  });

  doc.save(`KSP_Sentinel_Executive_Report_${Date.now()}.pdf`);
}
